import { PlantType, Zone } from './types.ts';

/** Structural constants (not balancing). */
export const GRID_SIZE = 64;
export const TICK_RATE = 4; // simulation ticks per real-time second at 1x speed
export const TICK_MS = 1000 / TICK_RATE;
export const SAVE_VERSION = 1;

/** One in-game day lasts 4 real-time minutes at 1x speed. */
export const TICKS_PER_DAY = 4 * 60 * TICK_RATE;

/** Samples kept in the energy history graph (one per in-game half hour). */
export const ENERGY_HISTORY_SAMPLES = 48;
export const TICKS_PER_HISTORY_SAMPLE = TICKS_PER_DAY / ENERGY_HISTORY_SAMPLES;

/**
 * Central balancing configuration. All gameplay tuning values live here —
 * no magic numbers in simulation code.
 *
 * Energy amounts are in abstract "energy units" (EU) per tick.
 */
export const BALANCE = {
  startingMoney: 25_000,

  costs: {
    roadPerTile: 10,
    bridgePerTile: 40,
    /** Avenue on land / over the river; upgrading a street pays the difference. */
    avenuePerTile: 30,
    /** Avenue on land / over the river; upgrading a street pays the difference. */
    avenueBridgePerTile: 90,
    /** Power line per tile on land; over river or lake it is an overhead crossing. */
    powerLinePerTile: 4,
    powerLineWaterPerTile: 12,
    zonePerTile: 5,
    insulation: 4_000,
    plant: {
      [PlantType.SolarFarm]: 1_200,
      [PlantType.WindTurbine]: 1_800,
      [PlantType.Battery]: 1_500,
      [PlantType.BiogasPlant]: 2_500,
      [PlantType.ChargingHub]: 800,
      [PlantType.Park]: 400,
      [PlantType.RunOfRiver]: 2_200,
      [PlantType.PumpedStorage]: 4_000,
      [PlantType.FireStation]: 1_500,
      [PlantType.PoliceStation]: 1_200,
    } as Record<PlantType, number>,
  },

  upkeepPerTick: {
    roadPerTile: 0.005,
    avenuePerTile: 0.012,
    powerLinePerTile: 0.0005,
    plant: {
      [PlantType.SolarFarm]: 0.05,
      [PlantType.WindTurbine]: 0.08,
      [PlantType.Battery]: 0.04,
      [PlantType.BiogasPlant]: 0.1,
      [PlantType.ChargingHub]: 0.02,
      [PlantType.Park]: 0.015,
      [PlantType.RunOfRiver]: 0.06,
      [PlantType.PumpedStorage]: 0.08,
      [PlantType.FireStation]: 0.06,
      [PlantType.PoliceStation]: 0.05,
    } as Record<PlantType, number>,
    /** Additional fuel cost per energy unit generated by biogas. */
    biogasFuelCostPerEnergyUnit: 0.15,
  },

  tax: {
    defaultRate: 0.1,
    maxRate: 0.3,
    /** Income per tick = rate * (population * perResident + jobs * perJob). */
    incomePerResident: 0.09,
    incomePerJob: 0.12,
    /** Tax rate above which happiness starts to suffer. */
    happinessNeutralRate: 0.12,
  },

  energy: {
    /** Peak PV output per solar farm at full sun, clear sky. */
    solarPeakOutput: 150,
    /** Peak output per wind turbine at windSpeed = 1. */
    windPeakOutput: 120,
    /** Wind output is proportional to windSpeed^3 (capped), like real turbines. */
    windCutInSpeed: 0.1,
    /** Energy a single battery can store. */
    batteryCapacity: 3_000,
    /** Max charge/discharge rate per battery per tick. */
    batteryPowerLimit: 120,
    /** Round-trip efficiency applied on charge. */
    batteryChargeEfficiency: 0.92,
    /** Dispatchable biogas output per plant per tick. */
    biogasMaxOutput: 90,
    /** Run-of-river output per plant per tick at full river flow. */
    hydroPeakOutput: 40,
    /** Pumped storage: one plant's capacity, power limit and efficiency. */
    pumpedStorageCapacity: 12_000,
    pumpedStoragePowerLimit: 200,
    pumpedStorageChargeEfficiency: 0.78,
    /**
     * Tiles around an energised line tile or a supply plant that count as
     * connected (Chebyshev distance).
     */
    lineSupplyRadius: 3,
    /**
     * Supply radius before power lines existed; only used to migrate saves
     * without a line layer.
     */
    legacySupplyRadius: 14,
    /**
     * Rooftop PV grows automatically with density: peak output per
     * building by density level 1..3 (only connected buildings feed in).
     */
    rooftopSolarPeakByDensity: [0, 0, 2, 6],
    /** Base consumption per building by zone and density level 1..3. */
    consumptionByZoneAndDensity: {
      [Zone.Residential]: [0, 2, 4.5, 8],
      [Zone.Commercial]: [0, 3, 6.5, 11],
      [Zone.Retail]: [0, 2.5, 5, 9],
    } as Record<Zone, number[]>,
    /**
     * Hourly load profile per zone (24 factors, index = hour). Residential
     * peaks in the morning and evening, commercial during office hours,
     * retail from daytime into the evening.
     */
    loadProfileByZone: {
      [Zone.Residential]: [
        0.3, 0.25, 0.22, 0.22, 0.25, 0.35, 0.6, 0.85, 0.7, 0.5, 0.45, 0.45, 0.5, 0.45, 0.45, 0.5,
        0.6, 0.8, 0.95, 1.0, 0.95, 0.8, 0.6, 0.4,
      ],
      [Zone.Commercial]: [
        0.15, 0.12, 0.12, 0.12, 0.15, 0.2, 0.4, 0.7, 0.95, 1.0, 1.0, 1.0, 0.95, 1.0, 1.0, 0.95,
        0.85, 0.6, 0.4, 0.3, 0.25, 0.2, 0.18, 0.15,
      ],
      [Zone.Retail]: [
        0.12, 0.1, 0.1, 0.1, 0.12, 0.15, 0.25, 0.45, 0.7, 0.9, 1.0, 1.0, 0.95, 0.95, 1.0, 1.0, 1.0,
        0.95, 0.9, 0.8, 0.6, 0.35, 0.2, 0.15,
      ],
    } as Record<Zone, number[]>,
  },

  market: {
    /**
     * The city has a limited transmission link to the wider (green)
     * grid: imports cover small deficits at a steep price, exports earn
     * a little instead of curtailing. Big shortfalls still black out.
     */
    importCapacity: 60,
    importCostPerEnergyUnit: 0.4,
    exportCapacity: 80,
    exportRevenuePerEnergyUnit: 0.03,
  },

  water: {
    /** River entry/exit stay this many tiles away from map corners. */
    edgeMargin: 4,
    /** Lateral meander amplitude as a fraction of the map size (two waves). */
    meanderAmplitudes: [0.12, 0.05] as const,
    /** Meander wave counts along the river. */
    meanderPeriods: [1.5, 3.2] as const,
    /** Per-row chance that a two-tile-wide section starts, and its length. */
    wideSectionChance: 0.08,
    wideSectionLength: 4,
    /** Lake diameter range in tiles. */
    lakeDiameter: [5, 9] as const,
    /** The lake sits this far (fraction) along the river. */
    lakePositionRange: [0.2, 0.8] as const,
    /** Evenly spaced lake position candidates within the range. */
    lakeCandidates: 13,
    /** Per-tile radius noise on the lake edge (0 = perfect ellipse). */
    lakeEdgeNoise: 0.3,
    /** Rain falls (and river flow rises) above this cloud cover. */
    rainCloudThreshold: 0.72,
    /** Flow gain per tick at full rain intensity. */
    rainRate: 0.003,
    /** Per-tick fraction of the distance to the dry baseline recovered. */
    dryRate: 0.001,
    dryBaselineFlow: 0.25,
    initialFlow: 0.5,
    /** Run-of-river output fraction at zero flow. */
    minFlowFactor: 0.4,
  },

  terrain: {
    /** Highest elevation level; levels run 0..maxLevel. */
    maxLevel: 7,
    /** Value-noise cell size in tiles (large = broad hills). */
    noiseCellSize: 12,
    /** Octave weights; octave i uses cell size noiseCellSize / 2^i. */
    octaveWeights: [1, 0.35] as const,
    /** Exponent shaping the height distribution toward low levels. */
    noiseExponent: 1.6,
    /** Levels of seed-chosen edge-to-edge tilt (ridges toward one edge). */
    tiltLevels: 3,
    /** Box-blur passes over the raw height field. */
    smoothingPasses: 2,
    /** Required fraction of land tiles with slope <= maxBuildSlope. */
    minBuildableFraction: 0.7,
    /** Extra blur passes tried before the flatten fallback kicks in. */
    maxSmoothingAttempts: 6,
    /** Largest slope (level difference to a neighbour) that stays buildable. */
    maxBuildSlope: 1,
    /** Cost multiplier for building on a sloped (slope >= 1) tile. */
    slopeCostFactor: 1.25,
    /** Wind turbine output bonus per elevation level of its tile. */
    windBonusPerLevel: 0.045,
    /** Run-of-river output bonus per level of drop at the plant tile. */
    hydroDropBonus: 0.2,
    /** Pumped-storage capacity/power bonus per level of head above the lake. */
    headBonusPerLevel: 0.12,
    /** Chebyshev radius scanned for the pumped-storage head (nearby hilltop). */
    headRadius: 2,
  },

  growth: {
    /** How many growth attempts happen per tick (seeded random tiles). */
    attemptsPerTick: 3,
    /** Demand must exceed this for a zone to spawn/densify buildings. */
    growthDemandThreshold: 0.05,
    /** Population/jobs provided per building by zone and density level 1..3. */
    populationByDensity: [0, 5, 12, 26],
    jobsByZoneAndDensity: {
      [Zone.Residential]: [0, 0, 0, 0],
      [Zone.Commercial]: [0, 4, 10, 22],
      [Zone.Retail]: [0, 3, 6, 12],
    } as Record<Zone, number[]>,
    /** Jobs the city can sustain per resident (service jobs etc. abstracted). */
    jobsPerResident: 0.65,
    /**
     * Residents a brand-new city attracts before any jobs exist, so growth
     * can bootstrap.
     */
    pioneerPopulation: 30,
    /**
     * Growth targets are scaled up by this factor so residential and
     * commercial demand can never BOTH fall under growthDemandThreshold at
     * the same time (which froze cities at ~300 residents). Must exceed
     * 1 / (1 - growthDemandThreshold).
     */
    demandHeadroom: 1.08,
    /** Retail floor space supported per resident + per job. */
    retailPerResident: 0.1,
    retailPerJob: 0.08,
    /** Ticks a building must be fully supplied before it can densify. */
    densifyMinAge: TICKS_PER_DAY / 4,
    /** Chance (0..1) that an eligible growth attempt succeeds. */
    growthChance: 0.6,
    /**
     * Abandonment: after this many ticks without full supply a building
     * starts to decay (one density level at a time, eventually emptying).
     * Only active once the energy system is in play (a plant exists).
     */
    abandonAfterTicks: TICKS_PER_DAY,
    /** Per-tick chance that an eligible troubled building decays. */
    abandonChancePerTick: 0.01,
  },

  happiness: {
    /** Smoothing factor per tick toward the target happiness. */
    smoothing: 0.02,
    base: 0.75,
    taxPenaltyWeight: 2.0,
    undersupplyPenaltyWeight: 0.6,
    /**
     * Max happiness bonus when every building has a park nearby; the
     * actual bonus scales with the share of buildings within parkRadius
     * (Chebyshev) of any park.
     */
    parksAndLightsBonus: 0.08,
    parkRadius: 6,
    /**
     * Commute penalty: when the average commute takes this factor
     * longer than free flow, happiness starts to suffer (scaled by
     * weight, capped).
     */
    commuteCongestionThreshold: 1.25,
    commutePenaltyWeight: 0.25,
    commuteMaxPenalty: 0.15,
    /** Below this happiness, growth stops entirely. */
    growthMinimum: 0.35,
  },

  vehicles: {
    /** One visible vehicle per this many (population + jobs). */
    citizensPerVehicle: 18,
    maxVehicles: 220,
    /** Tiles per second at 1x speed. */
    speedTilesPerSecond: 1.6,
    /** Energy drawn per tick by one actively charging vehicle. */
    chargingEnergyPerVehicle: 1.5,
    /** State-of-charge gained per tick while charging (0..1 scale). */
    chargeRatePerTick: 0.0012,
    /** State of charge consumed per road tile driven. */
    batteryDrainPerTile: 0.02,
    /** Below this SoC, smart charging charges regardless of surplus. */
    smartChargeFloor: 0.35,
    /** A hub serves workplaces within this Chebyshev radius. */
    hubRadius: 5,
    /** Vehicles per road tile AND direction (one lane each way) before followers must wait. */
    maxPerRoadTile: 2,
    /**
     * Ticks a blocked vehicle waits before it squeezes past anyway. Breaks
     * gridlocks (rings of full tiles) that would otherwise never clear.
     */
    maxWaitTicks: 40,
    /** Vehicles per lane on an avenue tile. */
    avenueMaxPerTile: 4,
    /** Avenue tiles are driven this much faster than streets. */
    avenueSpeedFactor: 1.5,
    /** Route cost multiplier applied per tile at full traffic load. */
    routeLoadPenalty: 2,
    /** Traffic load smoothing per tick (EMA weight of the current tick). */
    trafficLoadSmoothing: 0.05,
    /**
     * Commuting: vehicles drive home -> workplace in the morning and
     * back in the evening (hours of the in-game day). Departures are
     * spread over the window so traffic ramps up naturally.
     */
    commute: {
      morningStartHour: 6.5,
      eveningStartHour: 17.25,
      departureWindowHours: 1.5,
    },
    /** Vehicles one charging hub can serve simultaneously. */
    vehiclesPerHub: 25,
  },

  weather: {
    /** How fast cloud cover drifts (per tick). */
    cloudDrift: 0.003,
    windDrift: 0.002,
    /**
     * Multi-day pressure systems ("fronts") slowly shift the mean the
     * short-term weather noise reverts to. Two incommensurate periods per
     * quantity so calm sunny spells and dark doldrums (Dunkelflaute)
     * emerge naturally when the waves align. Periods in in-game days.
     */
    fronts: {
      cloud: { periodsDays: [2.6, 4.3] as const, amplitudes: [0.28, 0.12] as const, base: 0.45 },
      wind: { periodsDays: [3.4, 5.7] as const, amplitudes: [0.3, 0.1] as const, base: 0.5 },
    },
  },

  seasons: {
    /** A year has seasonsPerYear × daysPerSeason in-game days. */
    daysPerSeason: 5,
    /** Seasonal mean temperature swings between these (°C). */
    winterLow: -4,
    summerHigh: 24,
    /** Year phase of the warmest seasonal mean (late summer lag). */
    warmestPhase: 0.35,
    /** Diurnal cycle: ± this many °C, coldest at coldestTime (fraction of day). */
    diurnalAmplitude: 3,
    coldestTime: 0.2,
    /** Overcast daytime is cooler by up to this many °C. */
    cloudDamping: 2,
    /** Day length in hours at the shortest and longest day. */
    dayLengthHours: { shortest: 9.5, longest: 14.5 },
    /** Year phase of the longest day. */
    longestDayPhase: 0.3,
    /** Sun elevation factor at the shortest day (1 at the longest). */
    winterSolarStrength: 0.45,
    /** Front base offsets: +amplitude in winter, −amplitude in summer. */
    cloudBiasAmplitude: 0.12,
    windBiasAmplitude: 0.12,
    /** Precipitation below this temperature falls as snow (°C). */
    snowTemperature: 0,
    /** Snowpack melts above this temperature, meltRate per tick per °C. */
    meltTemperature: 2,
    meltRate: 0.0001,
    heating: {
      /** No heating above this temperature; full heating heatingRange below it. */
      comfortTemperature: 16,
      heatingRange: 20,
      /** Heating load at full cold as a multiple of the zone's base consumption. */
      weightByZone: {
        [Zone.Residential]: 0.8,
        [Zone.Commercial]: 0.45,
        [Zone.Retail]: 0.45,
      } as Record<Zone, number>,
      /** Heating multiplier once building insulation is bought. */
      insulationFactor: 0.5,
    },
    cooling: {
      /** No cooling at or below this temperature; full cooling coolingRange above it. */
      comfortTemperature: 20,
      coolingRange: 8,
      /** Cooling load at full heat as a multiple of the zone's base consumption. */
      weightByZone: {
        [Zone.Residential]: 0.26,
        [Zone.Commercial]: 0.45,
        [Zone.Retail]: 0.45,
      } as Record<Zone, number>,
      /** Cooling multiplier once building insulation is bought. */
      insulationFactor: 0.5,
    },
  },

  services: {
    fire: {
      /** Chebyshev radius (tiles) a fire station covers. */
      radius: 7,
    },
    police: {
      /** Chebyshev radius (tiles) a police station covers. */
      radius: 8,
    },
    /** Energy drawn per tick by one connected station. */
    stationConsumption: 2,
    /** Police consequences (happiness, tax) apply from this population on. */
    minPopulation: 100,
    /** Tax multiplier for buildings without police coverage. */
    uncoveredTaxFactor: 0.7,
    /** Max happiness penalty when no building has police coverage. */
    policePenaltyWeight: 0.1,
    /** Coverage share (per service) the safe-city goal requires. */
    goalCoverage: 0.9,
  },

  traffic: {
    /** Congestion factor (commute time over free flow) up to which traffic counts as flowing. */
    flowing: 1.15,
    /** Above this factor the HUD calls it a jam. */
    jammed: 1.5,
    /** Population the free-flow goal requires. */
    goalMinPopulation: 300,
  },
} as const;
